export const projects = [
  {
    id: "01",
    name: "Session Shelf",
    category: "DEVELOPER TOOLS",
    description:
      "A private home for your coding conversations. Browse, recap, and resume Claude Code and Codex sessions across computers — from a desktop app or your own private website.",
    short: "Your conversations. One place to pick them up.",
    platform: "Desktop & web",
    status: "In development",
    stack: ["TypeScript", "Electron", "React", "SQLite"],
    repo: "session-shelf",
    color: "#cefc78",
    symbol: "◈",
    shape: "ico",
    radius: 4.5,
    angle: 2.2,
  },
  {
    id: "02",
    name: "TI Oracle",
    category: "DATA & PREDICTIONS",
    description:
      "A Dota 2 research app that brings together match probabilities, tournament simulations, Fantasy projections, and hero matchup analysis. A Python data pipeline meets an interactive web interface.",
    short: "Finding the signal in the game.",
    platform: "Web & Python pipeline",
    status: "Research app",
    stack: ["Python", "Next.js", "FastAPI", "SQLite"],
    repo: "ti-oracle",
    color: "#c5bbfc",
    symbol: "◎",
    shape: "torus",
    radius: 6.6,
    angle: 5.4,
  },
  {
    id: "03",
    name: "Gaz",
    category: "OPERATIONAL SOFTWARE",
    description:
      "A fuel queue management platform connecting station operations, driver queues, and worker workflows. A monorepo with a NestJS backend, operational dashboards, and Flutter mobile applications.",
    short: "Less waiting. Better station operations.",
    platform: "Web & mobile",
    status: "MVP in progress",
    stack: ["NestJS", "Next.js", "Flutter", "PostgreSQL"],
    repo: "Gaz",
    color: "#ffad75",
    symbol: "✳",
    shape: "octa",
    radius: 8.7,
    angle: 3.5,
  },
  {
    id: "04",
    name: "WC26",
    category: "MACHINE LEARNING",
    description:
      "A World Cup prediction model combining Elo, recent form, squad quality, and match context. Goal models estimate outcomes, while Monte Carlo simulations explore how the tournament could unfold.",
    short: "A world of possibilities, modeled.",
    platform: "Python CLI & notebooks",
    status: "Research model",
    stack: ["Python", "XGBoost", "Poisson", "Monte Carlo"],
    repo: "wc26",
    color: "#84d7e4",
    symbol: "◉",
    shape: "sphere",
    radius: 10.7,
    angle: 0.55,
  },
];
